/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication4;

import java.awt.Checkbox;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Naman
 */
public  class details extends javax.swing.JFrame implements ActionListener {
    
Connection conn = new DBConnection().connect();
    /**
     * Creates new form Form
     */
    public details() {
        initComponents();
        

}
    
    
    public void setdetails(String s){
    clientname.setEditable(false);
    datecreated.setEditable(false);
    
    noofresources.setEditable(false);
    originalname.setEnabled(false);
       
    
    pseudoname.setEnabled(false);
    email.setEnabled(false);
    ats.setEnabled(false);
    jobboard.setEnabled(false);
    vms.setEnabled(false);
    phone.setEnabled(false);
    none.setEnabled(false);
    listofendclients.setEditable(false);
    servicelevelsagreed.setEditable(false);
    noofjobs.setEditable(false);
    noofexternalsubmittals.setEditable(false);
    noofplacements.setEditable(false);
    weeks4.setEnabled(false);
    weeks6.setEnabled(false);
    weeks8.setEnabled(false);
    noofweeks.setEditable(false);
    vmsscorecard.setEnabled(false);
    performancereport.setEnabled(false);
    vmsmsp.setEnabled(false);
    atsclients.setEditable(false);
    markups.setEditable(false);
    phonearea.setEditable(false);
    yes.setEnabled(false);
    no.setEnabled(false);
    weekly.setEditable(false);
    biweekly.setEditable(false);
    monthly.setEditable(false);
    training.setEditable(false);
    ims.setEditable(false);
    Phone.setEnabled(false);
    video.setEnabled(false);
    notinterviewing.setEnabled(false);
    providemsp.setEditable(false);
    additional.setEditable(false);
   
    
    String a=s;
    clientname.setText(a);
   
    
    String sql = "select * from userdata where cname like '%"+a+"%' ";
    try{
      PreparedStatement ps = conn.prepareStatement(sql);
       ResultSet rs = ps.executeQuery();
        while(rs.next()){
     datecreated.setText(rs.getString("date"));
    noofresources.setText(rs.getString("nresources"));
    originalname.setSelected(rs.getBoolean("oname"));
    pseudoname.setSelected(rs.getBoolean("pname"));
    email.setSelected(rs.getBoolean("email"));
    ats.setSelected(rs.getBoolean("ATS"));
    jobboard.setSelected(rs.getBoolean("JBoard"));
    vms.setSelected(rs.getBoolean("VMS"));
    phone.setSelected(rs.getBoolean("phone"));
    none.setSelected(rs.getBoolean("none"));
    listofendclients.setText(rs.getString("listofendclients"));
    servicelevelsagreed.setText(rs.getString("SLAPR"));
    noofjobs.setText(rs.getString("NOJW"));
    noofexternalsubmittals.setText(rs.getString("NESW"));
    noofplacements.setText(rs.getString("NOPM"));
    weeks4.setSelected(rs.getBoolean("4weeks"));
    weeks6.setSelected(rs.getBoolean("6weeks"));
    weeks8.setSelected(rs.getBoolean("8weeks"));
    noofweeks.setText(rs.getString("nweeks"));
    vmsscorecard.setSelected(rs.getBoolean("VMSscore"));
    performancereport.setSelected(rs.getBoolean("preport"));
    vmsmsp.setSelected(rs.getBoolean("VMSSLA"));
    atsclients.setText(rs.getString("ATSCI"));
    markups.setText(rs.getString("MSBC"));
    phonearea.setText(rs.getString("PAC"));
    yes.setSelected(rs.getBoolean("yes"));
    no.setSelected(rs.getBoolean("no"));
    weekly.setText(rs.getString("wrb"));
    biweekly.setText(rs.getString("bwrb"));
    monthly.setText(rs.getString("mrb"));
    training.setText(rs.getString("nresources"));
    ims.setText(rs.getString("IMSsrb"));
    Phone.setSelected(rs.getBoolean("interviewphone"));
    video.setSelected(rs.getBoolean("video"));
    notinterviewing.setSelected(rs.getBoolean("nointerview"));
    providemsp.setText(rs.getString("nameofMSPs"));
    additional.setText(rs.getString("comments"));
    }
        
    }catch(Exception e){
        
        
    }
    
    }
    
    
    
    
    
    
    
    
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        buttonGroup10 = new javax.swing.ButtonGroup();
        jLabel13 = new javax.swing.JLabel();
        jRadioButton5 = new javax.swing.JRadioButton();
        buttonGroup11 = new javax.swing.ButtonGroup();
        buttonGroup12 = new javax.swing.ButtonGroup();
        buttonGroup13 = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        phone = new javax.swing.JCheckBox();
        jobboard = new javax.swing.JCheckBox();
        Client_Name = new javax.swing.JLabel();
        vms = new javax.swing.JCheckBox();
        No_Of_Resources = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pseudoname = new javax.swing.JRadioButton();
        email = new javax.swing.JCheckBox();
        clientname = new javax.swing.JTextField();
        none = new javax.swing.JCheckBox();
        ats = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        originalname = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        noofresources = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        servicelevelsagreed = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        noofexternalsubmittals = new javax.swing.JTextField();
        noofjobs = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        noofplacements = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        weeks4 = new javax.swing.JCheckBox();
        weeks6 = new javax.swing.JCheckBox();
        weeks8 = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        vmsscorecard = new javax.swing.JCheckBox();
        performancereport = new javax.swing.JCheckBox();
        vmsmsp = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        atsclients = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        markups = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        phonearea = new javax.swing.JTextField();
        yes = new javax.swing.JCheckBox();
        no = new javax.swing.JCheckBox();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        weekly = new javax.swing.JTextField();
        biweekly = new javax.swing.JTextField();
        monthly = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        Phone = new javax.swing.JRadioButton();
        video = new javax.swing.JRadioButton();
        notinterviewing = new javax.swing.JRadioButton();
        jLabel23 = new javax.swing.JLabel();
        providemsp = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        ims = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        additional = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        training = new javax.swing.JTextPane();
        listofendclients = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        datecreated = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        noofweeks = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();

        jLabel13.setText("jLabel13");

        jRadioButton5.setText("jRadioButton5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane2.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jScrollPane2MouseWheelMoved(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Implementation Sheet", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Times New Roman", 1, 18))); // NOI18N
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N

        phone.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        phone.setText("Phone");

        jobboard.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jobboard.setText("Job Board(s)");

        Client_Name.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Client_Name.setText("Client Name :");

        vms.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        vms.setText("VMS");
        vms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vmsActionPerformed(evt);
            }
        });

        No_Of_Resources.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        No_Of_Resources.setText("No Of Resources :");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("List Of End_Clients :");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Client Providing :");

        buttonGroup1.add(pseudoname);
        pseudoname.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        pseudoname.setText("Pseudo Name");

        email.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        email.setText("email");
        email.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                emailItemStateChanged(evt);
            }
        });
        email.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emailMouseClicked(evt);
            }
        });
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });

        clientname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientnameActionPerformed(evt);
            }
        });

        none.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        none.setText("None");
        none.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noneActionPerformed(evt);
            }
        });

        ats.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ats.setText("ATS");
        ats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atsActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Client Prefer Recruiter To Use :");

        buttonGroup1.add(originalname);
        originalname.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        originalname.setText("Original Name");
        originalname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                originalnameActionPerformed(evt);
            }
        });

        noofresources.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noofresourcesActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Service levels Agreed (Per resource) :");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("No. of Jobs/ Week :");

        noofexternalsubmittals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noofexternalsubmittalsActionPerformed(evt);
            }
        });

        noofjobs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noofjobsActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("No. of External Submittals/ Week :");

        noofplacements.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noofplacementsActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("No. of Placements/ Month");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("What is the ramp-up time provided to client to meet SLAs or any temporary SLAs have been agreed?  ");

        weeks4.setText("4 Weeks");
        weeks4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weeks4ActionPerformed(evt);
            }
        });

        weeks6.setText("6 Weeks");
        weeks6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weeks6ActionPerformed(evt);
            }
        });

        weeks8.setText("8 Weeks");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText("Has the client shared following documents/reports to share past performance on clients being shared by IMS?");

        vmsscorecard.setText("VMS Scorecard");

        performancereport.setText(" Performance Report");
        performancereport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                performancereportActionPerformed(evt);
            }
        });

        vmsmsp.setText("VMS/MSP SLAs");
        vmsmsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vmsmspActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setText("Which ATS does client use internally?");

        atsclients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atsclientsActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setText("Mark-ups/Margins shared by client:");

        markups.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markupsActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel14.setText("Phone Area Code (if voice): ");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel15.setText("Have the recruiting and reporting templates\n been discussed and shared with Client?"); // NOI18N

        yes.setText("Yes");

        no.setText("No");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel16.setText("Account Management Review plan:");

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel17.setText("Weekly Review By  :");

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel18.setText("Bi-Weekly Review By :");

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel19.setText("Monthly Review By :");

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel20.setText("Training and Induction plan: ");

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel21.setText("IMS to share resumes by:");

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel22.setText("Client prefers to interview resources via:");

        buttonGroup11.add(Phone);
        Phone.setText("Phone");
        Phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhoneActionPerformed(evt);
            }
        });

        buttonGroup11.add(video);
        video.setText("Video");
        video.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                videoActionPerformed(evt);
            }
        });

        buttonGroup11.add(notinterviewing);
        notinterviewing.setText("Not Interviewing ");
        notinterviewing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notinterviewingActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel23.setText("Provide the names of MSPs for the clients being shared:");

        providemsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                providemspActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel24.setText("Additional Comments :");

        jScrollPane1.setViewportView(additional);

        jScrollPane3.setViewportView(training);

        jLabel25.setText("The above information is based on the phone and email conversations between client and IMS People’ executives during the prospecting and implementation stages. The information contained in this document is intended solely for the ");

        jLabel26.setText("This document contains confidential or legally privileged information.");

        jLabel27.setText("use of the individual or entity to whom it is shared and others authorized to receive it. This document contains confidential or legally privileged information.");

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Tahoma", 3, 13)); // NOI18N
        jLabel28.setText("date created");

        jLabel29.setText("Weeks");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(874, 874, 874)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(datecreated, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Client_Name)
                .addGap(432, 432, 432)
                .addComponent(clientname, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(No_Of_Resources)
                .addGap(406, 406, 406)
                .addComponent(noofresources, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(387, 387, 387)
                .addComponent(listofendclients, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(285, 285, 285)
                .addComponent(servicelevelsagreed, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(jLabel5)
                .addGap(130, 130, 130)
                .addComponent(noofjobs, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGap(302, 302, 302)
                .addComponent(noofexternalsubmittals, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(jLabel8)
                .addGap(93, 93, 93)
                .addComponent(noofplacements, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel9)
            .addComponent(jLabel10)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(504, 504, 504)
                .addComponent(vmsscorecard)
                .addGap(18, 18, 18)
                .addComponent(performancereport)
                .addGap(17, 17, 17)
                .addComponent(vmsmsp))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel11)
                .addGap(283, 283, 283)
                .addComponent(atsclients, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel12)
                .addGap(298, 298, 298)
                .addComponent(markups, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel14)
                .addGap(345, 345, 345)
                .addComponent(phonearea, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel15)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(518, 518, 518)
                .addComponent(yes)
                .addGap(136, 136, 136)
                .addComponent(no))
            .addComponent(jLabel16)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel17)
                .addGap(366, 366, 366)
                .addComponent(weekly, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel18)
                .addGap(352, 352, 352)
                .addComponent(biweekly, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel19)
                .addGap(367, 367, 367)
                .addComponent(monthly, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel20)
                .addGap(338, 338, 338)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(349, 349, 349)
                .addComponent(ims, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(248, 248, 248)
                .addComponent(Phone)
                .addGap(18, 18, 18)
                .addComponent(video)
                .addGap(18, 18, 18)
                .addComponent(notinterviewing))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel23)
                .addGap(173, 173, 173)
                .addComponent(providemsp, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel24)
                .addGap(375, 375, 375)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(564, 564, 564)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel25))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel27))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel26))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(409, 409, 409)
                .addComponent(email)
                .addGap(22, 22, 22)
                .addComponent(ats)
                .addGap(62, 62, 62)
                .addComponent(jobboard)
                .addGap(18, 18, 18)
                .addComponent(vms)
                .addGap(18, 18, 18)
                .addComponent(phone)
                .addGap(18, 18, 18)
                .addComponent(none))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(weeks4)
                        .addGap(18, 18, 18)
                        .addComponent(weeks6)
                        .addGap(18, 18, 18)
                        .addComponent(weeks8)
                        .addGap(18, 18, 18)
                        .addComponent(noofweeks, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(308, 308, 308)
                        .addComponent(originalname)
                        .addGap(83, 83, 83)
                        .addComponent(pseudoname)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel29))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(datecreated, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(122, 122, 122)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(Client_Name))
                    .addComponent(clientname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(No_Of_Resources))
                    .addComponent(noofresources, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(originalname)
                    .addComponent(pseudoname))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel1))
                    .addComponent(email)
                    .addComponent(ats)
                    .addComponent(jobboard)
                    .addComponent(vms)
                    .addComponent(phone)
                    .addComponent(none))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(listofendclients, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(servicelevelsagreed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(noofjobs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel7))
                    .addComponent(noofexternalsubmittals, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel8))
                    .addComponent(noofplacements, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(weeks4)
                    .addComponent(weeks6)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(weeks8)
                        .addComponent(noofweeks, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel29)))
                .addGap(26, 26, 26)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vmsscorecard)
                    .addComponent(performancereport)
                    .addComponent(vmsmsp))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel11))
                    .addComponent(atsclients, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel12))
                    .addComponent(markups, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(phonearea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(yes)
                    .addComponent(no))
                .addGap(11, 11, 11)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel17))
                    .addComponent(weekly, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel18))
                    .addComponent(biweekly, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel19))
                    .addComponent(monthly, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel21))
                    .addComponent(ims, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel22))
                    .addComponent(Phone)
                    .addComponent(video)
                    .addComponent(notinterviewing))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(providemsp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel27)
                .addGap(4, 4, 4)
                .addComponent(jLabel26))
        );

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1514, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void markupsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markupsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_markupsActionPerformed

    private void atsclientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atsclientsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_atsclientsActionPerformed

    private void vmsmspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vmsmspActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vmsmspActionPerformed

    private void performancereportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_performancereportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_performancereportActionPerformed

    private void noofplacementsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noofplacementsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noofplacementsActionPerformed

    private void noofjobsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noofjobsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noofjobsActionPerformed

    private void noofexternalsubmittalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noofexternalsubmittalsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noofexternalsubmittalsActionPerformed

    private void noofresourcesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noofresourcesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noofresourcesActionPerformed

    private void originalnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_originalnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_originalnameActionPerformed

    private void atsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_atsActionPerformed

    private void clientnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientnameActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
     
// TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void vmsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vmsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vmsActionPerformed

    private void noneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noneActionPerformed

        if(none.isSelected())
{
   phone.setEnabled(false);

   email.setEnabled(false);
   ats.setEnabled(false);
   jobboard.setEnabled(false);
   vms.setEnabled(false);
}
else{
    none.setEnabled(false);
}
    }//GEN-LAST:event_noneActionPerformed

    private void providemspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_providemspActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_providemspActionPerformed

    private void notinterviewingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notinterviewingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_notinterviewingActionPerformed

    private void PhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhoneActionPerformed

    private void videoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_videoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_videoActionPerformed

    private void weeks4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weeks4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weeks4ActionPerformed

    private void weeks6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weeks6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weeks6ActionPerformed

    private void emailItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_emailItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_emailItemStateChanged

    private void emailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailMouseClicked
   // TODO add your handling code here:
    }//GEN-LAST:event_emailMouseClicked

    private void jScrollPane2MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jScrollPane2MouseWheelMoved
jScrollPane2.getVerticalScrollBar().setUnitIncrement(28);        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane2MouseWheelMoved

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
this.dispose();
JTable_Search j = new JTable_Search();
j.show();
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Form().setVisible(true);
//            }
//        });
//    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
           
            public void run() {
                new details().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Client_Name;
    private javax.swing.JLabel No_Of_Resources;
    private javax.swing.JRadioButton Phone;
    private javax.swing.JTextPane additional;
    private javax.swing.JCheckBox ats;
    private javax.swing.JTextField atsclients;
    private javax.swing.JTextField biweekly;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup10;
    private javax.swing.ButtonGroup buttonGroup11;
    private javax.swing.ButtonGroup buttonGroup12;
    private javax.swing.ButtonGroup buttonGroup13;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JTextField clientname;
    private javax.swing.JTextField datecreated;
    private javax.swing.JCheckBox email;
    private javax.swing.JTextField ims;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JCheckBox jobboard;
    private javax.swing.JTextField listofendclients;
    private javax.swing.JTextField markups;
    private javax.swing.JTextField monthly;
    private javax.swing.JCheckBox no;
    private javax.swing.JCheckBox none;
    private javax.swing.JTextField noofexternalsubmittals;
    private javax.swing.JTextField noofjobs;
    private javax.swing.JTextField noofplacements;
    private javax.swing.JTextField noofresources;
    private javax.swing.JTextField noofweeks;
    private javax.swing.JRadioButton notinterviewing;
    private javax.swing.JRadioButton originalname;
    private javax.swing.JCheckBox performancereport;
    private javax.swing.JCheckBox phone;
    private javax.swing.JTextField phonearea;
    private javax.swing.JTextField providemsp;
    private javax.swing.JRadioButton pseudoname;
    private javax.swing.JTextField servicelevelsagreed;
    private javax.swing.JTextPane training;
    private javax.swing.JRadioButton video;
    private javax.swing.JCheckBox vms;
    private javax.swing.JCheckBox vmsmsp;
    private javax.swing.JCheckBox vmsscorecard;
    private javax.swing.JTextField weekly;
    private javax.swing.JCheckBox weeks4;
    private javax.swing.JCheckBox weeks6;
    private javax.swing.JCheckBox weeks8;
    private javax.swing.JCheckBox yes;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
