/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication4;

import java.awt.Checkbox;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemListener;
import java.sql.Connection;
import java.sql.PreparedStatement;

import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Naman
 */
public  class Form extends javax.swing.JFrame implements ActionListener {
Connection conn = new DBConnection().connect();
    /**
     * Creates new form Form
     */
    public Form() {
        initComponents();
        
Date.setFont(new Font("Times new Roman",Font.BOLD,16));

Time.setFont(new Font("Times new Roman",Font.BOLD,16));

 ShowDateTime();
}
    
     private void ShowDateTime()
     {
         Thread t = new Thread()
             
                 {
                     
                     @Override
                     public void run()
                 
                 {
                     for(;;)
                 {
                     Calendar Cal=new GregorianCalendar();
                     int date= Cal.get(Calendar.DAY_OF_MONTH);
                     int month=Cal.get(Calendar.MONTH)+1;
                     int year=Cal.get(Calendar.YEAR);
                     Date.setText("Date"+date+"/"+month+"/"+year);
               
                 int hours = Cal.get(Calendar.HOUR);
                 int min = Cal.get(Calendar.MINUTE);
                 int sec = Cal.get(Calendar.SECOND);
                 Time.setText("Time"+hours+":"+min+":"+sec);
                     try {
                         sleep(1000);
                     } catch (InterruptedException ex) {
                         Logger.getLogger(Form.class.getName()).log(Level.ALL.SEVERE, null, ex);
                     }
                     
                 }
                 }
                 
     };
         t.start();
                 }                 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        buttonGroup10 = new javax.swing.ButtonGroup();
        jLabel13 = new javax.swing.JLabel();
        jRadioButton5 = new javax.swing.JRadioButton();
        buttonGroup11 = new javax.swing.ButtonGroup();
        buttonGroup12 = new javax.swing.ButtonGroup();
        buttonGroup13 = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        phone = new javax.swing.JCheckBox();
        jobboard = new javax.swing.JCheckBox();
        Client_Name = new javax.swing.JLabel();
        vms = new javax.swing.JCheckBox();
        No_Of_Resources = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pseudoname = new javax.swing.JRadioButton();
        email = new javax.swing.JCheckBox();
        clientname = new javax.swing.JTextField();
        none = new javax.swing.JCheckBox();
        ats = new javax.swing.JCheckBox();
        Time = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        originalname = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        Date = new javax.swing.JLabel();
        noofresources = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        servicelevelsagreed = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        noofexternalsubmittals = new javax.swing.JTextField();
        noofjobs = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        noofplacements = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        weeks4 = new javax.swing.JCheckBox();
        weeks6 = new javax.swing.JCheckBox();
        weeks8 = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        vmsscorecard = new javax.swing.JCheckBox();
        performancereport = new javax.swing.JCheckBox();
        vmsmsp = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        atsclients = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        markups = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        phonearea = new javax.swing.JTextField();
        yes = new javax.swing.JCheckBox();
        no = new javax.swing.JCheckBox();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        weekly = new javax.swing.JTextField();
        biweekly = new javax.swing.JTextField();
        monthly = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        Phone = new javax.swing.JRadioButton();
        video = new javax.swing.JRadioButton();
        notinterviewing = new javax.swing.JRadioButton();
        jLabel23 = new javax.swing.JLabel();
        providemsp = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        ims = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        additional = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        training = new javax.swing.JTextPane();
        listofendclients = new javax.swing.JTextField();
        savebtn = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        noofweeks = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();

        jLabel13.setText("jLabel13");

        jRadioButton5.setText("jRadioButton5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane2.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jScrollPane2MouseWheelMoved(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Implementation Sheet", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Times New Roman", 1, 18))); // NOI18N
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        phone.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        phone.setText("Phone");
        jPanel1.add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(926, 310, -1, -1));

        jobboard.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jobboard.setText("Job Board(s)");
        jPanel1.add(jobboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(726, 310, -1, -1));

        Client_Name.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Client_Name.setText("Client Name :");
        jPanel1.add(Client_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 190, -1, -1));

        vms.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        vms.setText("VMS");
        vms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vmsActionPerformed(evt);
            }
        });
        jPanel1.add(vms, new org.netbeans.lib.awtextra.AbsoluteConstraints(849, 310, -1, -1));

        No_Of_Resources.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        No_Of_Resources.setText("No Of Resources :");
        jPanel1.add(No_Of_Resources, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 230, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("List Of End_Clients :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 354, -1, 20));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Client Providing :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 314, -1, -1));

        buttonGroup1.add(pseudoname);
        pseudoname.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        pseudoname.setText("Pseudo Name");
        jPanel1.add(pseudoname, new org.netbeans.lib.awtextra.AbsoluteConstraints(726, 267, -1, -1));

        email.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        email.setText("email");
        email.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                emailItemStateChanged(evt);
            }
        });
        email.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emailMouseClicked(evt);
            }
        });
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(524, 310, -1, -1));

        clientname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientnameActionPerformed(evt);
            }
        });
        jPanel1.add(clientname, new org.netbeans.lib.awtextra.AbsoluteConstraints(524, 187, 224, -1));

        none.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        none.setText("None");
        none.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noneActionPerformed(evt);
            }
        });
        jPanel1.add(none, new org.netbeans.lib.awtextra.AbsoluteConstraints(1011, 310, -1, -1));

        ats.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ats.setText("ATS");
        ats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atsActionPerformed(evt);
            }
        });
        jPanel1.add(ats, new org.netbeans.lib.awtextra.AbsoluteConstraints(609, 310, -1, -1));

        Time.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel1.add(Time, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 43, 167, 24));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Client Prefer Recruiter To Use :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 267, 210, 25));

        buttonGroup1.add(originalname);
        originalname.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        originalname.setText("Original Name");
        originalname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                originalnameActionPerformed(evt);
            }
        });
        jPanel1.add(originalname, new org.netbeans.lib.awtextra.AbsoluteConstraints(524, 267, -1, -1));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 28, 165, 20));

        Date.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel1.add(Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(1066, 39, 181, 28));

        noofresources.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noofresourcesActionPerformed(evt);
            }
        });
        jPanel1.add(noofresources, new org.netbeans.lib.awtextra.AbsoluteConstraints(524, 227, 224, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Service levels Agreed (Per resource) :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 396, -1, -1));
        jPanel1.add(servicelevelsagreed, new org.netbeans.lib.awtextra.AbsoluteConstraints(524, 393, 267, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("No. of Jobs/ Week :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(869, 396, -1, -1));

        noofexternalsubmittals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noofexternalsubmittalsActionPerformed(evt);
            }
        });
        jPanel1.add(noofexternalsubmittals, new org.netbeans.lib.awtextra.AbsoluteConstraints(524, 433, 267, -1));

        noofjobs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noofjobsActionPerformed(evt);
            }
        });
        jPanel1.add(noofjobs, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 393, 238, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("No. of External Submittals/ Week :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 438, -1, -1));

        noofplacements.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noofplacementsActionPerformed(evt);
            }
        });
        jPanel1.add(noofplacements, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 433, 238, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("No. of Placements/ Month");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(869, 436, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("What is the ramp-up time provided to client to meet SLAs or any temporary SLAs have been agreed?  ");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 473, -1, -1));

        weeks4.setText("4 Weeks");
        weeks4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weeks4ActionPerformed(evt);
            }
        });
        jPanel1.add(weeks4, new org.netbeans.lib.awtextra.AbsoluteConstraints(524, 508, -1, -1));

        weeks6.setText("6 Weeks");
        weeks6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weeks6ActionPerformed(evt);
            }
        });
        jPanel1.add(weeks6, new org.netbeans.lib.awtextra.AbsoluteConstraints(619, 508, -1, -1));

        weeks8.setText("8 Weeks");
        jPanel1.add(weeks8, new org.netbeans.lib.awtextra.AbsoluteConstraints(714, 508, -1, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText("Has the client shared following documents/reports to share past performance on clients being shared by IMS?");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 559, -1, -1));

        vmsscorecard.setText("VMS Scorecard");
        jPanel1.add(vmsscorecard, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 594, -1, -1));

        performancereport.setText(" Performance Report");
        performancereport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                performancereportActionPerformed(evt);
            }
        });
        jPanel1.add(performancereport, new org.netbeans.lib.awtextra.AbsoluteConstraints(645, 594, -1, -1));

        vmsmsp.setText("VMS/MSP SLAs");
        vmsmsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vmsmspActionPerformed(evt);
            }
        });
        jPanel1.add(vmsmsp, new org.netbeans.lib.awtextra.AbsoluteConstraints(809, 594, -1, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setText("Which ATS does client use internally?");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 652, -1, -1));

        atsclients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atsclientsActionPerformed(evt);
            }
        });
        jPanel1.add(atsclients, new org.netbeans.lib.awtextra.AbsoluteConstraints(524, 647, 235, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setText("Mark-ups/Margins shared by client:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 685, -1, -1));

        markups.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markupsActionPerformed(evt);
            }
        });
        jPanel1.add(markups, new org.netbeans.lib.awtextra.AbsoluteConstraints(524, 682, 235, -1));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel14.setText("Phone Area Code (if voice): ");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 711, -1, -1));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel15.setText("Have the recruiting and reporting templates\n been discussed and shared with Client?"); // NOI18N
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 751, -1, -1));
        jPanel1.add(phonearea, new org.netbeans.lib.awtextra.AbsoluteConstraints(525, 711, 234, -1));

        yes.setText("Yes");
        jPanel1.add(yes, new org.netbeans.lib.awtextra.AbsoluteConstraints(524, 777, -1, -1));

        no.setText("No");
        jPanel1.add(no, new org.netbeans.lib.awtextra.AbsoluteConstraints(709, 777, -1, -1));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel16.setText("Account Management Review plan:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 813, -1, -1));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel17.setText("Weekly Review By  :");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 853, -1, -1));

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel18.setText("Bi-Weekly Review By :");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 891, -1, -1));

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel19.setText("Monthly Review By :");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 933, -1, -1));
        jPanel1.add(weekly, new org.netbeans.lib.awtextra.AbsoluteConstraints(524, 848, 228, -1));
        jPanel1.add(biweekly, new org.netbeans.lib.awtextra.AbsoluteConstraints(524, 888, 228, -1));
        jPanel1.add(monthly, new org.netbeans.lib.awtextra.AbsoluteConstraints(524, 930, 228, -1));

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel20.setText("Training and Induction plan: ");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 986, -1, 25));

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel21.setText("IMS to share resumes by:");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 1129, 169, -1));

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel22.setText("Client prefers to interview resources via:");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 1170, 270, -1));

        buttonGroup11.add(Phone);
        Phone.setText("Phone");
        Phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhoneActionPerformed(evt);
            }
        });
        jPanel1.add(Phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(524, 1166, -1, -1));

        buttonGroup11.add(video);
        video.setText("Video");
        video.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                videoActionPerformed(evt);
            }
        });
        jPanel1.add(video, new org.netbeans.lib.awtextra.AbsoluteConstraints(605, 1166, -1, -1));

        buttonGroup11.add(notinterviewing);
        notinterviewing.setText("Not Interviewing ");
        notinterviewing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notinterviewingActionPerformed(evt);
            }
        });
        jPanel1.add(notinterviewing, new org.netbeans.lib.awtextra.AbsoluteConstraints(684, 1166, -1, -1));

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel23.setText("Provide the names of MSPs for the clients being shared:");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 1211, -1, 19));

        providemsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                providemspActionPerformed(evt);
            }
        });
        jPanel1.add(providemsp, new org.netbeans.lib.awtextra.AbsoluteConstraints(524, 1209, 228, -1));

        jLabel24.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel24.setText("Additional Comments :");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 1249, -1, -1));
        jPanel1.add(ims, new org.netbeans.lib.awtextra.AbsoluteConstraints(524, 1126, 228, -1));

        jScrollPane1.setViewportView(additional);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(524, 1249, 228, 120));

        jScrollPane3.setViewportView(training);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(524, 986, 228, 115));
        jPanel1.add(listofendclients, new org.netbeans.lib.awtextra.AbsoluteConstraints(524, 353, 267, -1));

        savebtn.setText("save");
        savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtnActionPerformed(evt);
            }
        });
        jPanel1.add(savebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 1380, 100, 50));

        jLabel25.setText("The above information is based on the phone and email conversations between client and IMS People’ executives during the prospecting and implementation stages. The information contained in this document is intended solely for the ");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1430, -1, 20));

        jLabel26.setText("This document contains confidential or legally privileged information.");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1470, -1, -1));

        jLabel27.setText("use of the individual or entity to whom it is shared and others authorized to receive it. This document contains confidential or legally privileged information.");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1450, -1, -1));

        jButton1.setText("reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 1380, 110, 50));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("HOME");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 1380, 100, 50));
        jPanel1.add(noofweeks, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 510, 30, -1));

        jLabel28.setText("Weeks");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 500, -1, 40));

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1514, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void markupsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markupsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_markupsActionPerformed

    private void atsclientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atsclientsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_atsclientsActionPerformed

    private void vmsmspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vmsmspActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vmsmspActionPerformed

    private void performancereportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_performancereportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_performancereportActionPerformed

    private void noofplacementsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noofplacementsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noofplacementsActionPerformed

    private void noofjobsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noofjobsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noofjobsActionPerformed

    private void noofexternalsubmittalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noofexternalsubmittalsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noofexternalsubmittalsActionPerformed

    private void noofresourcesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noofresourcesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noofresourcesActionPerformed

    private void originalnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_originalnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_originalnameActionPerformed

    private void atsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_atsActionPerformed

    private void clientnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientnameActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
     
// TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void vmsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vmsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vmsActionPerformed

    private void noneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noneActionPerformed

        if(none.isSelected())
{
    phone.setSelected(false);
   phone.setEnabled(false);
   email.setSelected(false);
   email.setEnabled(false);
   ats.setSelected(false);
   ats.setEnabled(false);
   jobboard.setSelected(false);
   jobboard.setEnabled(false);
   vms.setSelected(false);
   vms.setEnabled(false);
}
else{
    
    phone.setEnabled(true);

   email.setEnabled(true);
   ats.setEnabled(true);
   jobboard.setEnabled(true);
   vms.setEnabled(true);
}
    }//GEN-LAST:event_noneActionPerformed

    private void providemspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_providemspActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_providemspActionPerformed

    private void notinterviewingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notinterviewingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_notinterviewingActionPerformed

    private void PhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhoneActionPerformed

    private void videoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_videoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_videoActionPerformed

    private void weeks4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weeks4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weeks4ActionPerformed

    private void weeks6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weeks6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weeks6ActionPerformed

    private void emailItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_emailItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_emailItemStateChanged

    private void emailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailMouseClicked
   // TODO add your handling code here:
    }//GEN-LAST:event_emailMouseClicked

    private void jScrollPane2MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jScrollPane2MouseWheelMoved
jScrollPane2.getVerticalScrollBar().setUnitIncrement(28);        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane2MouseWheelMoved

    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed
       
    java.util.Date dt = new java.util.Date();

java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");

String currentTime = sdf.format(dt);
        String sql = " insert into userdata VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
        try{
    PreparedStatement ps;
    ps = conn.prepareStatement(sql);
    ps.setString(1, clientname.getText());
    ps.setString(2, noofresources.getText());
    ps.setBoolean(3, originalname.isSelected());
    ps.setBoolean(4, pseudoname.isSelected());
    ps.setBoolean(5, email.isSelected());
    ps.setBoolean(6, ats.isSelected());
    ps.setBoolean(7, jobboard.isSelected());
    ps.setBoolean(8, vms.isSelected());
    ps.setBoolean(9, phone.isSelected());
    ps.setBoolean(10, none.isSelected());
    ps.setString(11, listofendclients.getText());
    ps.setString(12, servicelevelsagreed.getText());
    ps.setString(13, noofjobs.getText());
    ps.setString(14, noofexternalsubmittals.getText());
    ps.setString(15, noofplacements.getText());
    ps.setBoolean(16, weeks4.isSelected());
    ps.setBoolean(17, weeks6.isSelected());
    ps.setBoolean(18, weeks8.isSelected());
    ps.setString(19, noofweeks.getText());
    ps.setBoolean(20, vmsscorecard.isSelected());
    ps.setBoolean(21, performancereport.isSelected());
    ps.setBoolean(22, vmsmsp.isSelected());
    ps.setString(23, atsclients.getText());
    ps.setString(24, markups.getText());
    ps.setString(25, phonearea.getText());
    ps.setBoolean(26, yes.isSelected());
    ps.setBoolean(27, no.isSelected());
    ps.setString(28, weekly.getText());
    ps.setString(29, biweekly.getText());
    ps.setString(30, monthly.getText());
    ps.setString(31, training.getText());
    ps.setString(32, ims.getText());
    ps.setBoolean(33, Phone.isSelected());
    ps.setBoolean(34, video.isSelected());
    ps.setBoolean(35, notinterviewing.isSelected());
    ps.setString(36, providemsp.getText());
    ps.setString(37, additional.getText());
    ps.setString(38, currentTime);
    int n1;
    n1=ps.executeUpdate();
    if(n1>0)
    {
        JOptionPane.showMessageDialog(null,"data entered");
    }
}
catch(Exception e)
{
    
}
    }//GEN-LAST:event_savebtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      
        
        
    clientname.setText("");
    noofresources.setText("");
    originalname.setSelected(false);
    pseudoname.setSelected(false);
    email.setSelected(false);
    ats.setSelected(false);
    jobboard.setSelected(false);
    vms.setSelected(false);
    phone.setSelected(false);
    none.setSelected(false);
    listofendclients.setText("");
    servicelevelsagreed.setText("");
    noofjobs.setText("");
    noofexternalsubmittals.setText("");
    noofplacements.setText("");
    weeks4.setSelected(false);
    weeks6.setSelected(false);
    weeks8.setSelected(false);
    noofweeks.setText("");
    vmsscorecard.setSelected(false);
    performancereport.setSelected(false);
    vmsmsp.setSelected(false);
    atsclients.setText("");
    markups.setText("");
    phonearea.setText("");
    yes.setSelected(false);
    no.setSelected(false);
    weekly.setText("");
    biweekly.setText("");
    monthly.setText("");
    training.setText("");
    ims.setText("");
    Phone.setSelected(false);
    video.setSelected(false);
    notinterviewing.setSelected(false);
    providemsp.setText("");
    additional.setText("");
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
this.dispose();
new login(null, true).show();
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Form().setVisible(true);
//            }
//        });
//    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
           
            public void run() {
                new Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Client_Name;
    private javax.swing.JLabel Date;
    private javax.swing.JLabel No_Of_Resources;
    private javax.swing.JRadioButton Phone;
    private javax.swing.JLabel Time;
    private javax.swing.JTextPane additional;
    private javax.swing.JCheckBox ats;
    private javax.swing.JTextField atsclients;
    private javax.swing.JTextField biweekly;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup10;
    private javax.swing.ButtonGroup buttonGroup11;
    private javax.swing.ButtonGroup buttonGroup12;
    private javax.swing.ButtonGroup buttonGroup13;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JTextField clientname;
    private javax.swing.JCheckBox email;
    private javax.swing.JTextField ims;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JCheckBox jobboard;
    private javax.swing.JTextField listofendclients;
    private javax.swing.JTextField markups;
    private javax.swing.JTextField monthly;
    private javax.swing.JCheckBox no;
    private javax.swing.JCheckBox none;
    private javax.swing.JTextField noofexternalsubmittals;
    private javax.swing.JTextField noofjobs;
    private javax.swing.JTextField noofplacements;
    private javax.swing.JTextField noofresources;
    private javax.swing.JTextField noofweeks;
    private javax.swing.JRadioButton notinterviewing;
    private javax.swing.JRadioButton originalname;
    private javax.swing.JCheckBox performancereport;
    private javax.swing.JCheckBox phone;
    private javax.swing.JTextField phonearea;
    private javax.swing.JTextField providemsp;
    private javax.swing.JRadioButton pseudoname;
    private javax.swing.JButton savebtn;
    private javax.swing.JTextField servicelevelsagreed;
    private javax.swing.JTextPane training;
    private javax.swing.JRadioButton video;
    private javax.swing.JCheckBox vms;
    private javax.swing.JCheckBox vmsmsp;
    private javax.swing.JCheckBox vmsscorecard;
    private javax.swing.JTextField weekly;
    private javax.swing.JCheckBox weeks4;
    private javax.swing.JCheckBox weeks6;
    private javax.swing.JCheckBox weeks8;
    private javax.swing.JCheckBox yes;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
