/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication7;

import java.awt.Font;
import static java.lang.Thread.sleep;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Naman
 */
public class PreFrame extends javax.swing.JFrame {
    Connection conn = new DBConnection().connect();

    /**
     * Creates new form PreFrame
     */
    public PreFrame() {
        initComponents();
        t7.setVisible(false);
        t8.setVisible(false);
       
    Date.setFont(new Font("Times new Roman",Font.BOLD,16));

Time.setFont(new Font("Times new Roman",Font.BOLD,16));

 ShowDateTime();
}
    
     private void ShowDateTime()
     {
         Thread t = new Thread()
             
                 {
                     
                     @Override
                     public void run()
                 
                 {
                     for(;;)
                 {
                     Calendar Cal=new GregorianCalendar();
                     int date= Cal.get(Calendar.DAY_OF_MONTH);
                     int month=Cal.get(Calendar.MONTH)+1;
                     int year=Cal.get(Calendar.YEAR);
                     Date.setText("Date"+date+"/"+month+"/"+year);
               
                 int hours = Cal.get(Calendar.HOUR);
                 int min = Cal.get(Calendar.MINUTE);
                 int sec = Cal.get(Calendar.SECOND);
                 Time.setText("Time"+hours+":"+min+":"+sec);
                     try {
                         sleep(1000);
                     } catch (InterruptedException ex) {
                         JOptionPane.showMessageDialog(null, ex);
                     }
                     
                 }
                 }
                 
     };
         t.start();
                 }                 


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jMenu1 = new javax.swing.JMenu();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        jScrollPane8 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        c4 = new javax.swing.JCheckBox();
        c2 = new javax.swing.JCheckBox();
        c3 = new javax.swing.JCheckBox();
        c5 = new javax.swing.JCheckBox();
        c6 = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        c8 = new javax.swing.JCheckBox();
        c10 = new javax.swing.JCheckBox();
        c9 = new javax.swing.JCheckBox();
        c11 = new javax.swing.JCheckBox();
        c12 = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        c7 = new javax.swing.JCheckBox();
        c20 = new javax.swing.JRadioButton();
        c19 = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        t9 = new javax.swing.JTextPane();
        c1 = new javax.swing.JCheckBox();
        c23 = new javax.swing.JCheckBox();
        c25 = new javax.swing.JCheckBox();
        c24 = new javax.swing.JCheckBox();
        c30 = new javax.swing.JCheckBox();
        c29 = new javax.swing.JCheckBox();
        jCheckBox28 = new javax.swing.JCheckBox();
        c27 = new javax.swing.JCheckBox();
        c28 = new javax.swing.JCheckBox();
        c31 = new javax.swing.JCheckBox();
        c33 = new javax.swing.JCheckBox();
        c26 = new javax.swing.JCheckBox();
        c34 = new javax.swing.JCheckBox();
        c32 = new javax.swing.JCheckBox();
        c35 = new javax.swing.JCheckBox();
        c36 = new javax.swing.JCheckBox();
        c38 = new javax.swing.JCheckBox();
        jLabel15 = new javax.swing.JLabel();
        c39 = new javax.swing.JCheckBox();
        c40 = new javax.swing.JCheckBox();
        c41 = new javax.swing.JCheckBox();
        c42 = new javax.swing.JCheckBox();
        c43 = new javax.swing.JCheckBox();
        c44 = new javax.swing.JCheckBox();
        c45 = new javax.swing.JCheckBox();
        jLabel16 = new javax.swing.JLabel();
        c46 = new javax.swing.JCheckBox();
        c47 = new javax.swing.JCheckBox();
        c48 = new javax.swing.JCheckBox();
        c49 = new javax.swing.JCheckBox();
        c51 = new javax.swing.JCheckBox();
        c52 = new javax.swing.JCheckBox();
        c53 = new javax.swing.JCheckBox();
        c54 = new javax.swing.JCheckBox();
        c55 = new javax.swing.JCheckBox();
        c50 = new javax.swing.JCheckBox();
        c56 = new javax.swing.JCheckBox();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        t17 = new javax.swing.JTextPane();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        t4 = new javax.swing.JTextField();
        t5 = new javax.swing.JTextField();
        t6 = new javax.swing.JTextField();
        t10 = new javax.swing.JTextField();
        t11 = new javax.swing.JTextField();
        t13 = new javax.swing.JTextField();
        t12 = new javax.swing.JTextField();
        t15 = new javax.swing.JTextField();
        t14 = new javax.swing.JTextField();
        t16 = new javax.swing.JTextField();
        t18 = new javax.swing.JTextField();
        t19 = new javax.swing.JTextField();
        t20 = new javax.swing.JTextField();
        t7 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        c13 = new javax.swing.JCheckBox();
        c14 = new javax.swing.JCheckBox();
        c15 = new javax.swing.JCheckBox();
        c16 = new javax.swing.JCheckBox();
        c17 = new javax.swing.JCheckBox();
        c18 = new javax.swing.JCheckBox();
        c37 = new javax.swing.JCheckBox();
        t8 = new javax.swing.JTextField();
        c57 = new javax.swing.JRadioButton();
        c58 = new javax.swing.JRadioButton();
        c21 = new javax.swing.JRadioButton();
        c22 = new javax.swing.JRadioButton();
        submit = new javax.swing.JButton();
        Date = new javax.swing.JLabel();
        Time = new javax.swing.JLabel();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("jCheckBoxMenuItem2");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pre Implentation Call Datasheet");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pre Implementation Call Sheet", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18))); // NOI18N
        jPanel1.setMinimumSize(new java.awt.Dimension(0, 0));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Client's Name :");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Source :");

        c4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        c4.setText("Email Campaign");

        c2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        c2.setText("Website Enquiry");
        c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2ActionPerformed(evt);
            }
        });

        c3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        c3.setText("Business Advisor ");
        c3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c3ActionPerformed(evt);
            }
        });

        c5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        c5.setText("Client Referral");
        c5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c5ActionPerformed(evt);
            }
        });

        buttonGroup1.add(c6);
        c6.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        c6.setText("Other");
        c6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c6ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Executive POC Name:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Phone :");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Title :");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Email :");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Company Size :");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Client’s Business Model :");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Company Turnover :");

        buttonGroup2.add(c8);
        c8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        c8.setText("11-50");

        buttonGroup2.add(c10);
        c10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        c10.setText("201-500");
        c10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c10ActionPerformed(evt);
            }
        });

        buttonGroup2.add(c9);
        c9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        c9.setText("51-200");
        c9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c9ActionPerformed(evt);
            }
        });

        buttonGroup2.add(c11);
        c11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        c11.setText("501-1000");
        c11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c11ActionPerformed(evt);
            }
        });

        buttonGroup2.add(c12);
        c12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        c12.setText("1000+");
        c12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c12ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText("Company HQ Address :");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setText("Has the client allocated a budget for outsourcing? ");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setText("What is Client’s objective and goal ");

        buttonGroup2.add(c7);
        c7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        c7.setText("1-10");

        buttonGroup4.add(c20);
        c20.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        c20.setText("No");
        c20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c20ActionPerformed(evt);
            }
        });

        buttonGroup4.add(c19);
        c19.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        c19.setText("Yes");
        c19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c19ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel14.setText("Domains/Industries Serving:");

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jLabel24.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jScrollPane1.setViewportView(t9);

        c1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        c1.setText("Conference");

        c23.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        c23.setText("Information Technolgy");

        c25.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        c25.setText("Engineering");

        c24.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        c24.setText("Financial / Banking");

        c30.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        c30.setText("Retail");

        c29.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        c29.setText("Oil & Gas / Utility");

        jCheckBox28.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jCheckBox28.setText("Pharmaceutical");

        c27.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        c27.setText("Federal/Govt.");

        c28.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        c28.setText("Digital/Professional/Creative");

        c31.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        c31.setText("Telecommunications");

        c33.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        c33.setText("Consulting");

        c26.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        c26.setText("Healthcare");

        c34.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        c34.setText("Others");

        c32.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        c32.setText("Pharmaceutical");

        buttonGroup6.add(c35);
        c35.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        c35.setText("Direct Relationship");

        buttonGroup6.add(c36);
        c36.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        c36.setText("Retail / Botique");

        buttonGroup6.add(c38);
        c38.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        c38.setText("Others");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel15.setText("Documents requested by client :");

        buttonGroup7.add(c39);
        c39.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        c39.setText("Proposal");
        c39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c39ActionPerformed(evt);
            }
        });

        buttonGroup7.add(c40);
        c40.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        c40.setText("ORS Agreement");
        c40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c40ActionPerformed(evt);
            }
        });

        buttonGroup7.add(c41);
        c41.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        c41.setText("Case Studies");
        c41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c41ActionPerformed(evt);
            }
        });

        buttonGroup7.add(c42);
        c42.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        c42.setText("Process Literature");
        c42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c42ActionPerformed(evt);
            }
        });

        buttonGroup7.add(c43);
        c43.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        c43.setText("IMS Templates");
        c43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c43ActionPerformed(evt);
            }
        });

        buttonGroup7.add(c44);
        c44.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        c44.setText("Others");
        c44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c44ActionPerformed(evt);
            }
        });

        buttonGroup8.add(c45);
        c45.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        c45.setText("Voice Recruting");
        c45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c45ActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel16.setText("Services Offered/Requested :");

        buttonGroup8.add(c46);
        c46.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        c46.setText("Voice Pre-Screening");
        c46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c46ActionPerformed(evt);
            }
        });

        buttonGroup8.add(c47);
        c47.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        c47.setText("Sourcing");
        c47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c47ActionPerformed(evt);
            }
        });

        buttonGroup8.add(c48);
        c48.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        c48.setText("Email Pre-Screening");
        c48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c48ActionPerformed(evt);
            }
        });

        buttonGroup8.add(c49);
        c49.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        c49.setText("Database Reactivation");
        c49.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c49ActionPerformed(evt);
            }
        });

        buttonGroup8.add(c51);
        c51.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        c51.setText("Lead Generation (Voice)");
        c51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c51ActionPerformed(evt);
            }
        });

        buttonGroup8.add(c52);
        c52.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        c52.setText("Lead Generation (NV)");
        c52.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c52ActionPerformed(evt);
            }
        });

        buttonGroup8.add(c53);
        c53.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        c53.setText("VMS Management");
        c53.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c53ActionPerformed(evt);
            }
        });

        buttonGroup8.add(c54);
        c54.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        c54.setText("Admin Coordinator");
        c54.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c54ActionPerformed(evt);
            }
        });

        buttonGroup8.add(c55);
        c55.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        c55.setText("Data Entry");
        c55.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c55ActionPerformed(evt);
            }
        });

        buttonGroup8.add(c50);
        c50.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        c50.setText("Resume Writing");
        c50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c50ActionPerformed(evt);
            }
        });

        buttonGroup8.add(c56);
        c56.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        c56.setText("Others");
        c56.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c56ActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel17.setText("Success Statement/SLA Expectations: ");

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel18.setText("Tentative Go Live Date:");

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel20.setText("Tentative No. of Resources Required:");

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel21.setText("Pricing Discussed (Per resource per month) :");

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel22.setText("Volume Discount Offered :");

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel23.setText("Fixed Cost (USD)");

        jLabel25.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel25.setText("Variable Cost :");

        jLabel26.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel26.setText("Other Cost (Job Board) :");

        jLabel27.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel27.setText("Additional Comments :");

        jScrollPane2.setViewportView(t17);

        jLabel28.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel28.setText("Project Awarded to (IMS VP):");

        jLabel29.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel29.setText("Sales Executive:");

        jLabel30.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel30.setText("Follow-up Date:");

        t3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t3ActionPerformed(evt);
            }
        });

        t6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t6ActionPerformed(evt);
            }
        });

        t13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t13ActionPerformed(evt);
            }
        });

        t18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t18ActionPerformed(evt);
            }
        });

        t7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t7ActionPerformed(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel31.setText("Has the client engaged any offshore");

        jLabel32.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel32.setText("recruiting company in the past");

        jLabel33.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel33.setText("for considering to outsource?");

        buttonGroup3.add(c13);
        c13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        c13.setText("Less than $1 M");

        buttonGroup3.add(c14);
        c14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        c14.setText("$1M - $10M");

        buttonGroup3.add(c15);
        c15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        c15.setText("$11M - $50M");

        buttonGroup3.add(c16);
        c16.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        c16.setText("$51M - $200M");

        buttonGroup3.add(c17);
        c17.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        c17.setText("$201M-$500M");
        c17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c17ActionPerformed(evt);
            }
        });

        buttonGroup3.add(c18);
        c18.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        c18.setText("$501M - $1000M");
        c18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c18ActionPerformed(evt);
            }
        });

        buttonGroup6.add(c37);
        c37.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        c37.setText("VMS / MSP");

        c57.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        c57.setText("Yes");

        c58.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        c58.setText("No");

        buttonGroup9.add(c21);
        c21.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        c21.setText("Yes");
        c21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c21ActionPerformed(evt);
            }
        });

        buttonGroup9.add(c22);
        c22.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        c22.setText("No");
        c22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c22ActionPerformed(evt);
            }
        });

        submit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        Date.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Date.setText("Date : ");

        Time.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Time.setText("Time : ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)))
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel32)
                            .addComponent(jLabel31)
                            .addComponent(jLabel12))
                        .addGap(60, 60, 60)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(c1)
                                        .addGap(18, 18, 18)
                                        .addComponent(c2)
                                        .addGap(18, 18, 18)
                                        .addComponent(c3))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(c7)
                                        .addGap(18, 18, 18)
                                        .addComponent(c8)
                                        .addGap(18, 18, 18)
                                        .addComponent(c9)
                                        .addGap(18, 18, 18)
                                        .addComponent(c10)
                                        .addGap(18, 18, 18)
                                        .addComponent(c11))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addGap(126, 126, 126)
                                            .addComponent(t8))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(c19)
                                            .addGap(18, 18, 18)
                                            .addComponent(c20)
                                            .addGap(18, 18, 18)
                                            .addComponent(t7, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(c4)
                                        .addGap(18, 18, 18)
                                        .addComponent(c5)
                                        .addGap(18, 18, 18)
                                        .addComponent(c6))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(c12))))
                            .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t4, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t5, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t6, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(c13)
                                .addGap(18, 18, 18)
                                .addComponent(c14)
                                .addGap(18, 18, 18)
                                .addComponent(c15)
                                .addGap(18, 18, 18)
                                .addComponent(c16)
                                .addGap(18, 18, 18)
                                .addComponent(c17)
                                .addGap(18, 18, 18)
                                .addComponent(c18))
                            .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13)
                            .addComponent(jLabel33)
                            .addComponent(jLabel14)
                            .addComponent(jLabel8)
                            .addComponent(jLabel15)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(174, 174, 174)
                                .addComponent(jLabel19))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(224, 224, 224)
                                .addComponent(jLabel24))
                            .addComponent(jLabel18)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27)
                            .addComponent(jLabel28)
                            .addComponent(jLabel29)
                            .addComponent(jLabel30))
                        .addGap(92, 92, 92)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t20, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t19, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t18, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(c51)
                                .addGap(18, 18, 18)
                                .addComponent(c52)
                                .addGap(18, 18, 18)
                                .addComponent(c53)
                                .addGap(18, 18, 18)
                                .addComponent(c54)
                                .addGap(18, 18, 18)
                                .addComponent(c55)
                                .addGap(18, 18, 18)
                                .addComponent(c56))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(c23)
                                    .addGap(18, 18, 18)
                                    .addComponent(c24)
                                    .addGap(18, 18, 18)
                                    .addComponent(c25)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(c26))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(c27)
                                    .addGap(18, 18, 18)
                                    .addComponent(c28)
                                    .addGap(18, 18, 18)
                                    .addComponent(c29)
                                    .addGap(18, 18, 18)
                                    .addComponent(c30)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(c31)
                                        .addGap(18, 18, 18)
                                        .addComponent(c32))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(c35)
                                        .addGap(18, 18, 18)
                                        .addComponent(c36))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(c39)
                                        .addGap(18, 18, 18)
                                        .addComponent(c40)
                                        .addGap(18, 18, 18)
                                        .addComponent(c41)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(c37)
                                        .addGap(28, 28, 28)
                                        .addComponent(c38))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(c33)
                                        .addGap(30, 30, 30)
                                        .addComponent(c34))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(c42)
                                        .addGap(18, 18, 18)
                                        .addComponent(c43)
                                        .addGap(18, 18, 18)
                                        .addComponent(c44)
                                        .addGap(809, 809, 809)
                                        .addComponent(jCheckBox28))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(c45)
                                .addGap(18, 18, 18)
                                .addComponent(c46)
                                .addGap(18, 18, 18)
                                .addComponent(c47)
                                .addGap(18, 18, 18)
                                .addComponent(c48)
                                .addGap(18, 18, 18)
                                .addComponent(c49)
                                .addGap(18, 18, 18)
                                .addComponent(c50))
                            .addComponent(t10, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t11, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t12, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(t13, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(t14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(t15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(t16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(c57)
                                .addGap(18, 18, 18)
                                .addComponent(c58))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(c21)
                                .addGap(18, 18, 18)
                                .addComponent(c22))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(328, 328, 328)
                        .addComponent(submit))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(760, 760, 760)
                        .addComponent(Date)
                        .addGap(133, 133, 133)
                        .addComponent(Time)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Date)
                    .addComponent(Time))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(c1)
                        .addComponent(c2)
                        .addComponent(c3)
                        .addComponent(c4)
                        .addComponent(c6)
                        .addComponent(c5))
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(t5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(c7)
                    .addComponent(c8)
                    .addComponent(c9)
                    .addComponent(c10)
                    .addComponent(c11)
                    .addComponent(c12))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(c13)
                    .addComponent(c14)
                    .addComponent(c15)
                    .addComponent(c16)
                    .addComponent(c17)
                    .addComponent(c18))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(t6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel32)
                            .addComponent(t7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel31)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(c19)
                        .addComponent(c20)))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(t8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c21)
                    .addComponent(c22))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel33)
                        .addGap(53, 53, 53)
                        .addComponent(jLabel11))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(c23)
                            .addComponent(jLabel14)
                            .addComponent(c24)
                            .addComponent(c25)
                            .addComponent(c26))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(c27)
                            .addComponent(c28)
                            .addComponent(c29)
                            .addComponent(c30))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(c31)
                            .addComponent(c32)
                            .addComponent(c33)
                            .addComponent(c34))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jCheckBox28)
                        .addGap(102, 102, 102)
                        .addComponent(jLabel19)
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel16)
                                .addComponent(t10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel24)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(c35)
                                    .addComponent(jLabel8)
                                    .addComponent(c36)
                                    .addComponent(c37)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(c38)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(c39)
                                .addComponent(c40)
                                .addComponent(c41)
                                .addComponent(c42)
                                .addComponent(c43)
                                .addComponent(c44)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(c45)
                            .addComponent(c46)
                            .addComponent(c47)
                            .addComponent(c48)
                            .addComponent(c49)
                            .addComponent(c50))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(c51)
                            .addComponent(c52)
                            .addComponent(c53)
                            .addComponent(c54)
                            .addComponent(c55)
                            .addComponent(c56))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(t11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(t12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(t13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(c57)
                    .addComponent(c58))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(t14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(t15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(t16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel30))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(t19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(t20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(submit)
                .addContainerGap())
        );

        jScrollPane8.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 1388, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 1700, Short.MAX_VALUE)
        );

        jScrollPane8.getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t18ActionPerformed

    private void c56ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c56ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c56ActionPerformed

    private void c50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c50ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c50ActionPerformed

    private void c55ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c55ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c55ActionPerformed

    private void c54ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c54ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c54ActionPerformed

    private void c53ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c53ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c53ActionPerformed

    private void c52ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c52ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c52ActionPerformed

    private void c51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c51ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c51ActionPerformed

    private void c49ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c49ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c49ActionPerformed

    private void c48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c48ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c48ActionPerformed

    private void c47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c47ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c47ActionPerformed

    private void c46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c46ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c46ActionPerformed

    private void c45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c45ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c45ActionPerformed

    private void c44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c44ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c44ActionPerformed

    private void c43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c43ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c43ActionPerformed

    private void c42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c42ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c42ActionPerformed

    private void c41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c41ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c41ActionPerformed

    private void c40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c40ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c40ActionPerformed

    private void c39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c39ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c39ActionPerformed

    private void c12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c12ActionPerformed

    private void c11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c11ActionPerformed

    private void c9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c9ActionPerformed

    private void c10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c10ActionPerformed

    private void c6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c6ActionPerformed

    private void c5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c5ActionPerformed

    private void c3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c3ActionPerformed

    private void c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c2ActionPerformed

    private void c19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c19ActionPerformed
if(c19.isSelected())
{
    t7.setVisible(true);
}
// TODO add your handling code here:
    }//GEN-LAST:event_c19ActionPerformed

    private void c20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c20ActionPerformed
if(c20.isSelected())
{
    t7.setVisible(false);
}// TODO add your handling code here:
    }//GEN-LAST:event_c20ActionPerformed

    private void t6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t6ActionPerformed

    private void t7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t7ActionPerformed

    private void t3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t3ActionPerformed

    private void c17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c17ActionPerformed

    private void c18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c18ActionPerformed

    private void t13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t13ActionPerformed

    private void c21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c21ActionPerformed
if(c19.isSelected())
{
    t8.setVisible(true);
}        // TODO add your handling code here:
    }//GEN-LAST:event_c21ActionPerformed

    private void c22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c22ActionPerformed
if(c19.isSelected())
{
    t8.setVisible(false);
}        // TODO add your handling code here:
    }//GEN-LAST:event_c22ActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
      String sql = "Insert into userdata VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ";
      try{
          PreparedStatement ps;
          ps = conn.prepareStatement(sql);
          ps.setString(1,t1.getText());
          ps.setBoolean(2, c1.isSelected());
          ps.setBoolean(3, c2.isSelected());
          ps.setBoolean(4, c3.isSelected());
          ps.setBoolean(5, c4.isSelected());
          ps.setBoolean(6, c5.isSelected());
          ps.setBoolean(7, c6.isSelected());
          ps.setString(8,t2.getText());
          ps.setString(9,t3.getText());
          ps.setString(10,t4.getText());
          ps.setString(11,t5.getText());
          ps.setBoolean(12, c7.isSelected());
          ps.setBoolean(13, c8.isSelected());
          ps.setBoolean(14, c9.isSelected());
          ps.setBoolean(15, c10.isSelected());
          ps.setBoolean(16, c11.isSelected());
          ps.setBoolean(17, c12.isSelected());
          ps.setBoolean(18, c13.isSelected());
          ps.setBoolean(19, c14.isSelected());
          ps.setBoolean(20, c15.isSelected());
          ps.setBoolean(21, c16.isSelected());
          ps.setBoolean(22, c17.isSelected());
          ps.setBoolean(23, c18.isSelected());
          ps.setString(24,t6.getText());
          ps.setBoolean(25, c19.isSelected());
          ps.setBoolean(26, c20.isSelected());
          ps.setString(27,t7.getText());
          ps.setBoolean(28, c21.isSelected());
          ps.setBoolean(29, c22.isSelected());
          ps.setString(30,t8.getText());
          ps.setString(31,t9.getText());
          ps.setBoolean(32, c23.isSelected());
          ps.setBoolean(33, c24.isSelected());
          ps.setBoolean(34, c25.isSelected());
          ps.setBoolean(35, c26.isSelected());
          ps.setBoolean(36, c27.isSelected());
          ps.setBoolean(37, c28.isSelected());
          ps.setBoolean(38, c29.isSelected());
          ps.setBoolean(39, c30.isSelected());
          ps.setBoolean(40, c31.isSelected());
          ps.setBoolean(41, c32.isSelected());
          ps.setBoolean(42, c33.isSelected());
          ps.setBoolean(43, c34.isSelected());
          ps.setBoolean(44, c35.isSelected());
          ps.setBoolean(45, c36.isSelected());
          ps.setBoolean(46, c37.isSelected());
          ps.setBoolean(47, c38.isSelected());
          ps.setBoolean(48, c39.isSelected());
          ps.setBoolean(49, c40.isSelected());
          ps.setBoolean(50, c41.isSelected());
          ps.setBoolean(51, c42.isSelected());
          ps.setBoolean(52, c43.isSelected());
          ps.setBoolean(53, c44.isSelected());
          ps.setBoolean(54, c45.isSelected());
          ps.setBoolean(55, c46.isSelected());
          ps.setBoolean(56, c47.isSelected());
          ps.setBoolean(57, c48.isSelected());
          ps.setBoolean(58, c49.isSelected());
          ps.setBoolean(59, c50.isSelected());
          ps.setBoolean(60, c51.isSelected());
          ps.setBoolean(61, c52.isSelected());
          ps.setBoolean(62, c53.isSelected());
          ps.setBoolean(63, c54.isSelected());
          ps.setBoolean(64, c55.isSelected());
          ps.setBoolean(65, c56.isSelected());
          ps.setString(66,t10.getText());
          ps.setString(67,t11.getText());
          ps.setString(68,t12.getText());
          ps.setString(69,t13.getText());
          ps.setBoolean(70, c57.isSelected());
          ps.setBoolean(71, c58.isSelected());
          ps.setString(72,t14.getText());
          ps.setString(73,t15.getText());
          ps.setString(74,t16.getText());
          ps.setString(75,t17.getText());
          ps.setString(76,t18.getText());
          ps.setString(77,t19.getText());
          ps.setString(78,t20.getText());
          
          int n1=ps.executeUpdate();
          if(n1>0){
          JOptionPane.showMessageDialog(null, "data entered");
          }
      }catch(Exception e){
      }
    }//GEN-LAST:event_submitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PreFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PreFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PreFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PreFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PreFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Date;
    private javax.swing.JLabel Time;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JCheckBox c1;
    private javax.swing.JCheckBox c10;
    private javax.swing.JCheckBox c11;
    private javax.swing.JCheckBox c12;
    private javax.swing.JCheckBox c13;
    private javax.swing.JCheckBox c14;
    private javax.swing.JCheckBox c15;
    private javax.swing.JCheckBox c16;
    private javax.swing.JCheckBox c17;
    private javax.swing.JCheckBox c18;
    private javax.swing.JRadioButton c19;
    private javax.swing.JCheckBox c2;
    private javax.swing.JRadioButton c20;
    private javax.swing.JRadioButton c21;
    private javax.swing.JRadioButton c22;
    private javax.swing.JCheckBox c23;
    private javax.swing.JCheckBox c24;
    private javax.swing.JCheckBox c25;
    private javax.swing.JCheckBox c26;
    private javax.swing.JCheckBox c27;
    private javax.swing.JCheckBox c28;
    private javax.swing.JCheckBox c29;
    private javax.swing.JCheckBox c3;
    private javax.swing.JCheckBox c30;
    private javax.swing.JCheckBox c31;
    private javax.swing.JCheckBox c32;
    private javax.swing.JCheckBox c33;
    private javax.swing.JCheckBox c34;
    private javax.swing.JCheckBox c35;
    private javax.swing.JCheckBox c36;
    private javax.swing.JCheckBox c37;
    private javax.swing.JCheckBox c38;
    private javax.swing.JCheckBox c39;
    private javax.swing.JCheckBox c4;
    private javax.swing.JCheckBox c40;
    private javax.swing.JCheckBox c41;
    private javax.swing.JCheckBox c42;
    private javax.swing.JCheckBox c43;
    private javax.swing.JCheckBox c44;
    private javax.swing.JCheckBox c45;
    private javax.swing.JCheckBox c46;
    private javax.swing.JCheckBox c47;
    private javax.swing.JCheckBox c48;
    private javax.swing.JCheckBox c49;
    private javax.swing.JCheckBox c5;
    private javax.swing.JCheckBox c50;
    private javax.swing.JCheckBox c51;
    private javax.swing.JCheckBox c52;
    private javax.swing.JCheckBox c53;
    private javax.swing.JCheckBox c54;
    private javax.swing.JCheckBox c55;
    private javax.swing.JCheckBox c56;
    private javax.swing.JRadioButton c57;
    private javax.swing.JRadioButton c58;
    private javax.swing.JCheckBox c6;
    private javax.swing.JCheckBox c7;
    private javax.swing.JCheckBox c8;
    private javax.swing.JCheckBox c9;
    private javax.swing.JCheckBox jCheckBox28;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JButton submit;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t10;
    private javax.swing.JTextField t11;
    private javax.swing.JTextField t12;
    private javax.swing.JTextField t13;
    private javax.swing.JTextField t14;
    private javax.swing.JTextField t15;
    private javax.swing.JTextField t16;
    private javax.swing.JTextPane t17;
    private javax.swing.JTextField t18;
    private javax.swing.JTextField t19;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t20;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    private javax.swing.JTextField t7;
    private javax.swing.JTextField t8;
    private javax.swing.JTextPane t9;
    // End of variables declaration//GEN-END:variables
}
